# Generated by Django 5.1.3 on 2024-11-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/No_Image_Available.png', null=True, upload_to=''),
        ),
    ]
